Tab Controller, not finished, with error
austimkelly/riverdata-react-native pull request #3
Opened 2022-11-15 22:36 UTC by HenryJames4

2022-11-15 23:07 UTC, austimkelly commented on riverdata/App.js
> +      <Tabs />
@HenryJames4 See https://reactnavigation.org/docs/nesting-navigators

It looks like having a Tab controller inside of a navigation stack is a no-no.
Here's the error I get when running `npm run ios`

```
ERROR  Error: Another navigator is already registered for this container. You likely have multiple navigators under a single "NavigationContainer" or "Screen". Make sure each navigator is under a separate "Screen" container. See https://reactnavigation.org/docs/nesting-navigators for a guide on nesting.

This error is located at:
    in BottomTabNavigator (created by Tabs)
    in Tabs (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

2022-11-15 23:07 UTC, austimkelly requested changes
Please review nested navigation comment and adjust accordingly.

2022-12-02 01:52 UTC, HenryJames4 commented
Tab controller is now functional, it is set as a stack screen inside the navigation container. However, it does not display on "State Site", "Site Gauges", and "Gauge Graph". Still trying to figure out how to get these stacks of screens to persist under the tab controller.

2022-12-06 22:11 UTC, JP0512 approved these changes
@HenryJames4 I merged your change and tested them. They look good to me.

2022-12-06 22:12 UTC, austimkelly approved these changes
LGTM. Tested with @JP0512

2022-12-06 22:12 UTC, merged